### ISSUE TITLE
minishift service foo - Should support service context-path annotations

### ISSUE THREAD

**Issue by davsclaus** [jimmidyson/minishift#76]
A service can be annotated in kubernetes to include a prefix path for the service, such as `/hello` in this example: https://github.com/rhuss/fabric8-maven-plugin/blob/master/samples/external-resources/src/main/fabric8/service.yml

In my example then I type `minshift service hello` and it opens

    http://192.168.64.5:32623/

But with the annotated the context-path should include `/hello` eg so its

    http://192.168.64.5:32623/hello

In my own project I manually declare a service so I can specify that context-path annotation but also show how to chose port numbers for the service

I have a `src/main/fabric8/service.yml` file with some kubenetes metadata:
```
metadata:
  annotations:
    api.service.kubernetes.io/path: /hello
  name: "hello"
spec:
  ports:
  - port: 8181
    protocol: "TCP"
    targetPort: 8080
  type: LoadBalancer
```
